# Generated by Django 3.0.6 on 2020-05-13 16:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('in_ex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expance',
            new_name='Expanse',
        ),
    ]
